---
- name: detect if rubies are installed
  command: '{{ rvm1 }} {{ item }} do true'
  changed_when: false
  failed_when: false
  register: detect_rubies
  with_items: rvm1_rubies
  when: rvm1_rubies

- name: ensure rubies are installed
  command: '{{ rvm1 }} install {{ item.item }}'
  when: rvm1_rubies and item.rc != 0
  with_items: detect_rubies.results

- name: detect default ruby version
  command: '{{ rvm1 }} alias list default'
  changed_when: false
  register: detect_default_ruby_version

- name: ensure default ruby is selected
  command: '{{ rvm1 }} alias create default {{ rvm1_default_ruby_version }}'
  when: detect_default_ruby_version.stdout == '' or rvm1_default_ruby_version not in detect_default_ruby_version.stdout

- name: ensure rvm install path is writable by the set owner:group
  file: path='{{ rvm1_install_path }}' state=directory recurse=yes owner='{{ rvm1_user }}' group='{{ rvm1_group }}'